GROQ_API_KEY="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"
OPENAI_API_KEY="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"
REDDIT_CLIENT_ID="zEU_3ix9-H2mKpvTP5peTg"
REDDIT_CLIENT_SECRET="WlCE6A_qsZszDpLaBBoKlz6MX_6tew"
TAVILY_API_KEY="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"